export enum ActionTypeEnum {
  REGISTER_ACCOUNT = "REGISTER_ACCOUNT",
  REGISTER_ACCOUNT_WITH_GOOGLE = "REGISTER_ACCOUNT_WITH_GOOGLE",
  LOGIN_ACCOUNT = "LOGIN_ACCOUNT",
  LOGIN_ACCOUNT_WITH_GOOGLE = "LOGIN_ACCOUNT_WITH_GOOGLE",
  CHECK_USER_EXISTS = "CHECK_USER_EXISTS",
  LOG_OUT = "LOG_OUT",
  SAVE_PRODUCTS_IN_DB = "SAVE_PRODUCTS_IN_DB",
  GET_PRODUCTS = "GET_PRODUCTS",
  SAVE_PRODUCT_IN_DB = "SAVE_PRODUCT_IN_DB",
  UPDATE_USER_HEALTH_DATA = "UPDATE_USER_HEALTH_DATA",
  ON_BOARDING_STATUS = "ON_BOARDING_STATUS",
  REMOVE_PRODUCT_FROM_DB = "REMOVE_PRODUCT_FROM_DB",
  GET_HEALTH_PROFILE = "GET_HEALTH_PROFILE",
  GET_LATEST_APP_VERSION = "GET_LATEST_APP_VERSION",
  UPDATE_APP_VERSION = "UPDATE_APP_VERSION",
  SAVE_PRODUCT_IN_UNIQUE_PRODUCT_DB = "SAVE_PRODUCT_IN_UNIQUE_PRODUCT_DB",
  GET_UNIQUE_PRODUCTS = "GET_UNIQUE_PRODUCTS",
  USER_PURCHASE_SUCCESS = "USER_PURCHASE_SUCCESS",
  USER_PURCHASE_ERROR = "USER_PURCHASE_ERROR",
  USER_PURCHASE_CONNECTED = "USER_PURCHASE_CONNECTED",
  // should remove later on
  CHECK_HELLO_WORLD_FUNCTION = "CHECK_HELLO_WORLD_FUNCTION",
  GET_SUBSCRIPTION_PRICE = "GET_SUBSCRIPTION_PRICE",
  USER_SUBSCRIPTION_UPDATE = "USER_SUBSCRIPTION_UPDATE",
}

export interface UserAction {
  action_type: ActionTypeEnum;
  action_description: string;
  action_data: string | null;
  date_format: string;
}
