export const LanguageKey = {
  // Permissions
  REQUEST_CAMERA_PERMISSION: "REQUEST_CAMERA_PERMISSION",
  CAMERA_PERMISSION_REQUIRED: "CAMERA_PERMISSION_REQUIRED",
  NEED_CAMERA_PERMISSION: "NEED_CAMERA_PERMISSION",
  GRANT_PERMISSION: "GRANT_PERMISSION",

  // Actions
  CANCEL: "CANCEL",
  CONTINUE: "CONTINUE",
  DONE: "DONE",
  NEXT: "NEXT",
  SKIP: "SKIP",
  SCAN_AGAIN: "SCAN_AGAIN",

  // Onboarding
  SLIDE_1_TITLE: "SLIDE_1_TITLE",
  SLIDE_1_SUBTITLE: "SLIDE_1_SUBTITLE",
  SLIDE_2_TITLE: "SLIDE_2_TITLE",
  SLIDE_2_SUBTITLE: "SLIDE_2_SUBTITLE",
  SLIDE_3_TITLE: "SLIDE_3_TITLE",
  SLIDE_3_SUBTITLE: "SLIDE_3_SUBTITLE",
  SLIDE_4_TITLE: "SLIDE_4_TITLE",
  SLIDE_4_SUBTITLE: "SLIDE_4_SUBTITLE",
  SLIDE_5_TITLE: "SLIDE_5_TITLE",
  SLIDE_5_SUBTITLE: "SLIDE_5_SUBTITLE",

  // Product
  INGREDIENTS_TITLE: "INGREDIENTS_TITLE",
  INGREDIENTS_NOT_FOUND: "INGREDIENTS_NOT_FOUND",
  PRODUCT_DETAILS: "PRODUCT_DETAILS",
  PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",

  // Ingredient Types
  TEXT: "TEXT",
  PERCENT: "PERCENT",
  PERCENT_MAX: "PERCENT_MAX",
  PERCENT_MIN: "PERCENT_MIN",
  PERCENT_ESTIMATE: "PERCENT_ESTIMATE",

  // UI States
  LOADING: "LOADING",
  SELECT_LANGUAGE: "SELECT_LANGUAGE",
  CONNECTION_ERROR: "CONNECTION_ERROR",

  // Health Conditions
  DIABETES: "DIABETES",
  HIGH_BLOOD_PRESSURE: "HIGH_BLOOD_PRESSURE",
  PREGNANT_NURSING: "PREGNANT_NURSING",
  TAKING_MEDICATIONS: "TAKING_MEDICATIONS",
  WEIGHT_MANAGEMENT: "WEIGHT_MANAGEMENT",
  HEART_DISEASE: "HEART_DISEASE",
  ARTHRITIS: "ARTHRITIS",
  ASTHMA: "ASTHMA",
  KIDNEY_DISEASE: "KIDNEY_DISEASE",
  LIVER_DISEASE: "LIVER_DISEASE",
  THYROID_ISSUES: "THYROID_ISSUES",
  CELIAC_DISEASE: "CELIAC_DISEASE",
  IBS: "IBS",
  OSTEOPOROSIS: "OSTEOPOROSIS",
  ANEMIA: "ANEMIA",

  // Allergens
  TREE_NUTS: "TREE_NUTS",
  DAIRY: "DAIRY",
  GLUTEN: "GLUTEN",
  EGGS: "EGGS",
  SHELLFISH: "SHELLFISH",
  SOY: "SOY",
  FISH: "FISH",
  SESAME: "SESAME",
  PEANUTS: "PEANUTS",
  MOLLUSKS: "MOLLUSKS",
  SULFITES: "SULFITES",
  MSG: "MSG",
  NIGHTSHADES: "NIGHTSHADES",
  HISTAMINE: "HISTAMINE",
  ARTIFICIAL_COLORS: "ARTIFICIAL_COLORS",
  CORN: "CORN",
  CITRUS: "CITRUS",
  STRAWBERRIES: "STRAWBERRIES",
  CHOCOLATE: "CHOCOLATE",
  MUSHROOMS: "MUSHROOMS",
  KIWI: "KIWI",
  AVOCADO: "AVOCADO",
  BANANA: "BANANA",
  COCONUT: "COCONUT",
  MUSTARD: "MUSTARD",
  CELERY: "CELERY",

  // Dietary Preferences
  VEGETARIAN: "VEGETARIAN",
  VEGAN: "VEGAN",
  KETO: "KETO",
  LOW_CARB: "LOW_CARB",
  LOW_SODIUM: "LOW_SODIUM",
  LOW_SUGAR: "LOW_SUGAR",
  PALEO: "PALEO",
  GLUTEN_FREE: "GLUTEN_FREE",

  HEALTH_PROFILE_SETUP: "HEALTH_PROFILE_SETUP",
} as const;
