# name: Build Android AAB

# on:
#   workflow_dispatch:
#   push:
#     branches: 
#       - main
#       - master

# jobs:
#   build-android:
#     runs-on: ubuntu-latest
    
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
      
#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: '18'
#           cache: 'npm'
      
#       - name: Setup Java
#         uses: actions/setup-java@v4
#         with:
#           distribution: 'temurin'
#           java-version: '21'  # Changed from 17 to 21
      
#       - name: Setup Android SDK
#         uses: android-actions/setup-android@v3
      
#       - name: Create google-services.json
#         run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > google-services.json
      
#       - name: Install dependencies
#         run: npm ci
      
#       - name: Clean dependencies
#         run: |
#           npm run clean || true
#           rm -rf node_modules/.cache || true
      
#       - name: Generate Android project
#         run: npx expo prebuild --platform android --clean
      
#       - name: Make gradlew executable
#         run: chmod +x android/gradlew
      
#       - name: Clean Gradle cache
#         run: |
#           cd android
#           ./gradlew clean
      
#       - name: Build AAB
#         run: |
#           cd android
#           ./gradlew bundleRelease --no-daemon --stacktrace
      
#       - name: Upload AAB as artifact
#         uses: actions/upload-artifact@v4
#         with:
#           name: android-aab
#           path: android/app/build/outputs/bundle/release/app-release.aab
#           retention-days: 30

name: Build Android AAB

on:
  workflow_dispatch:
  push:
    branches: 
      - main
      - master

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      
      - name: Create google-services.json
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > google-services.json
      
      - name: Install dependencies
        run: npm ci
      
      - name: Clean dependencies
        run: |
          npm run clean || true
          rm -rf node_modules/.cache || true
      
      - name: Generate Android project
        run: npx expo prebuild --platform android --clean
      
      - name: Setup release keystore
        run: |
          mkdir -p android/app
          echo "=== Debug keystore secret (first 50 chars) ==="
          echo '${{ secrets.KEYSTORE_FILE }}' | head -c 50
          echo ""
          echo "=== Secret length ==="
          echo '${{ secrets.KEYSTORE_FILE }}' | wc -c
          echo "=== Cleaning and decoding keystore ==="
          # Remove any whitespace/newlines and decode
          echo '${{ secrets.KEYSTORE_FILE }}' | tr -d '[:space:]' | base64 -d > android/app/keystore.jks
          echo "=== Keystore file created ==="
          ls -la android/app/keystore.jks
          file android/app/keystore.jks
          echo "=== Keystore file size ==="
          wc -c android/app/keystore.jks
          
      - name: Create keystore.properties
        run: |
          cat > android/keystore.properties << EOF
          storeFile=keystore.jks
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          EOF
          echo "=== keystore.properties created ==="
          cat android/keystore.properties
      
      - name: Verify keystore
        run: |
          cd android
          echo "=== Listing ALL aliases in keystore ==="
          keytool -list -keystore app/keystore.jks -storepass '${{ secrets.KEYSTORE_PASSWORD }}'
          echo ""
          echo "=== Trying to use the configured alias ==="
          keytool -list -keystore app/keystore.jks -storepass '${{ secrets.KEYSTORE_PASSWORD }}' -alias '${{ secrets.KEY_ALIAS }}' -v || echo "Configured alias failed"
      
      - name: Completely replace build.gradle signing configuration
        run: |
          cd android/app
          
          # Create backup
          cp build.gradle build.gradle.backup
          
          # Use sed to replace the buildTypes section entirely
          cat > signing_replacement.gradle << 'EOF'
          
              signingConfigs {
                  release {
                      def keystorePropertiesFile = rootProject.file("keystore.properties")
                      if (keystorePropertiesFile.exists()) {
                          def keystoreProperties = new Properties()
                          keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
                          
                          storeFile file(keystoreProperties['storeFile'])
                          storePassword keystoreProperties['storePassword']
                          keyAlias keystoreProperties['keyAlias']
                          keyPassword keystoreProperties['keyPassword']
                      }
                  }
              }
          
              buildTypes {
                  debug {
                      signingConfig signingConfigs.debug
                      applicationIdSuffix ".debug"
                      debuggable true
                  }
                  release {
                      signingConfig signingConfigs.release
                      minifyEnabled false
                      proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
                  }
              }
          EOF
          
          # Find where buildTypes starts and replace it
          python3 << 'EOF'
          import re
          
          with open('build.gradle', 'r') as f:
              content = f.read()
          
          with open('signing_replacement.gradle', 'r') as f:
              replacement = f.read()
          
          # First add signingConfigs and buildTypes after android {
          # Remove existing buildTypes section if it exists
          content = re.sub(r'buildTypes\s*{[^}]*}', '', content, flags=re.DOTALL)
          
          # Insert our replacement after android {
          content = re.sub(r'(android\s*{)', r'\1' + replacement, content, flags=re.DOTALL)
          
          with open('build.gradle', 'w') as f:
              f.write(content)
          EOF
          
          echo "=== Modified build.gradle ==="
          cat build.gradle
      
      - name: Make gradlew executable
        run: chmod +x android/gradlew
      
      - name: Clean Gradle cache
        run: |
          cd android
          ./gradlew clean
      
      - name: Debug signing configuration
        run: |
          cd android
          ./gradlew signingReport
      
      - name: Build AAB with explicit signing
        run: |
          cd android
          ./gradlew bundleRelease \
            -Pandroid.injected.signing.store.file=app/keystore.jks \
            -Pandroid.injected.signing.store.password='${{ secrets.KEYSTORE_PASSWORD }}' \
            -Pandroid.injected.signing.key.alias='${{ secrets.KEY_ALIAS }}' \
            -Pandroid.injected.signing.key.password='${{ secrets.KEY_PASSWORD }}' \
            --no-daemon --stacktrace
      
      - name: Verify AAB signing
        run: |
          cd android
          echo "=== Verifying AAB signature ==="
          keytool -printcert -jarfile app/build/outputs/bundle/release/app-release.aab | head -20
      
      - name: Upload AAB as artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-aab
          path: android/app/build/outputs/bundle/release/app-release.aab
          retention-days: 30